### ISSUE TITLE
Onscreen Launchpad/Midi Device

### ISSUE THREAD

**Issue by TrizekYT** [Vexcited/lpadder#18]
- Allow users to enable and disable an onscreen launchpad so they can share their screen to show their friends instead of having to turn on the camera

- Have the ability to create projects efficiently with the use of the onscreen launchpad

**Comment by Vexcited** [comment]
This is already something, it will be something that looks like [MicroLight](https://www.kaskobi.com/microlight) from Kaskobi.

The simulated device will be bound with the same events that the actual Launchpad, so even on collabs, people will have the exact same thing on their launchpad and on the onscreen launchpad ! Looks insane right ? Now I need to code that lmao...

I'll close this issue since it's already in the code, here <https://github.com/Vexcited/lpadder/blob/main/src/components/Launchpad.tsx>.
